to_static: False
enable_pass: False
use_amp: False
max_predictions_per_seq: 20
learning_rate: 0.0001
weight_decay: 0.01
adam_epsilon: 0.000001
warmup_steps: 10000
output_dir: ./tmp2/
logging_steps: 10
save_steps: 20000
max_steps: 1000
input_dir: ./data/wikicorpus_en_seqlen512/
model_type: bert
model_name_or_path: bert-large-uncased
batch_size: 2
use_pure_fp16: False
